### ISSUE TITLE
WXPusher 消息类型参数错误

### ISSUE THREAD

**Issue by ransxd** [Virace/bilibili-live-push#1]
日志输出：
[Time Monitoring]: Func: database.get_time, Time Spent: 0.2

[Time Monitoring]: Func: database.update_time, Time Spent: 0.07

未提供 PUSH_PLUS_TOKEN.

未提供 COOL_PUSH_TOKEN.

generated an exception: _type取值范围1~3
触发器附加信息：
{
  "1":{
            "leancloud_oid": "oid",
            "wxpusher_type" : "1",
            "wxpusher_topicids" : [123],
            "wxpusher_url" : "https://live.bilibili.com/1"
           }
}

实际上附加信息不填wxpusher_type就正常

**Comment by Virace** [comment]
wxpusher_type 是 数字类型，不需要添加双引号。
